Created="javafml"
loaderVersion="[21)"
license="MIT"

[[mods]]
modId="colormix"
veversion2.2.0"
displayName="Color Mixing"
authors="NonKungCh"
description="Dynamic color mixing for Minecraft 1.21+ Created by NonKungCh."

[[dependencies.colormix]]
modId="neoforge"
type="required"
version="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.colormix]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.12)"
ordering="NONE"
side="BOBOTH

