modLoader="javafml"
loaderVersion="[21)"
license="MIT"

[[mods]]
modId="colormix"
version="2.1.0"
displayName="Color Mixing"
authors="NonKungCh"
description="Dynamic color mixing for Minecraft 1.21.1 Created by NonKungCh."

[[dependencies.colormix]]
modId="neoforge"
type="required"
version="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.colormix]]
modId="minecraft"
type="required"
version="[1.21.1)"
ordering="NONE"
side="BOTH"
